// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfm5y9PZg_GQp1Rszo2bjGfBN_bVEWQck',
    appId: '1:237556484430:web:39e1fc415d4f6dcd2cf61f',
    messagingSenderId: '237556484430',
    projectId: 'panket-970cb',
    authDomain: 'panket-970cb.firebaseapp.com',
    storageBucket: 'panket-970cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG2k3UYGojo3H3yU9Wn3Z2HiCJ98avK8A',
    appId: '1:237556484430:android:d9bcb7c2af0115f22cf61f',
    messagingSenderId: '237556484430',
    projectId: 'panket-970cb',
    storageBucket: 'panket-970cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtD4BjoNnOVUZQjiVtguBddWBk3jRvVF0',
    appId: '1:237556484430:ios:53960a1b045a6a562cf61f',
    messagingSenderId: '237556484430',
    projectId: 'panket-970cb',
    storageBucket: 'panket-970cb.firebasestorage.app',
    iosBundleId: 'com.panket.panket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtD4BjoNnOVUZQjiVtguBddWBk3jRvVF0',
    appId: '1:237556484430:ios:53960a1b045a6a562cf61f',
    messagingSenderId: '237556484430',
    projectId: 'panket-970cb',
    storageBucket: 'panket-970cb.firebasestorage.app',
    iosBundleId: 'com.panket.panket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfm5y9PZg_GQp1Rszo2bjGfBN_bVEWQck',
    appId: '1:237556484430:web:2e026249370cbe0a2cf61f',
    messagingSenderId: '237556484430',
    projectId: 'panket-970cb',
    authDomain: 'panket-970cb.firebaseapp.com',
    storageBucket: 'panket-970cb.firebasestorage.app',
  );
}
